[project]
name = "fullstack-template"
version = "0.1.0"
description = "A template so I can build my fullstack apps"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0",
]
